### PR TITLE
Add "Services" field in the Operation struct

### PR DESCRIPTION
**Pull request by utkarsh-pro**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by kumarabd** [comment]
@mgfeller does this sound right? I am skeptical about this, more towards not doing it.

**Comment by kumarabd** [comment]
@utkarsh-pro possible to upgrade to the new mesh kit release here?

**Comment by mgfeller** [comment]
> @mgfeller does this sound right? I am skeptical about this, more towards not doing it.

Not quite sure myself @kumarabd and @utkarsh-pro what's your reasoning? Why should it (not) be here?
Workloads expose on or more services, usually, and it is practical to get the name of them so that you can look them up (using the func GetServiceEndpoint in meshkit) to get  access. Is it these kind of services we're thinking about here? 
Should that field be here or up to the individual adapters?

**Comment by kumarabd** [comment]
@mgfeller agreed with the usecase, skeptical about the implementation. Should it be a part of typed parameter or under additional features? Basically inside the map[string]string

**Comment by mgfeller** [comment]
@kumarabd ah I see :smile: As services are something most workloads expose, and are of general interest, it can be useful to have as fixed fields. In my mind, fixed fields are for information that is almost mandatory to provide, at least to consider explicitly by the maintainer. Also easier to follow in code.
Hmm, still not quite decided, but I tend to keep that as field.

**Comment by kumarabd** [comment]
That decides this then, this is good to go.

**Pull request merged**
