### PR TITLE
[Kubernetes] Cannot ping adapters when meshery deployed in Kubernetes

### PR DESCRIPTION
**Pull request by mgfeller**
Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>

**Description**

This PR fixes https://github.com/layer5io/meshery/issues/2603

**Notes for Reviewers**

Let's discuss this. If ok, a couple of test should be re-run (in-cluster, outside of cluster).

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Looks good to me.

**Comment by kumarabd** [comment]
@mgfeller This is already been done in meshkit - https://github.com/layer5io/meshkit/blob/master/utils/kubernetes/client.go#L15-L38. We just had to bump the version of meshkit to adapt the change.

**Comment by mgfeller** [comment]
@kumarabd @leecalcote ok, pitty I didn't know that earlier, used quite a few hours on that tbh

**Comment by kumarabd** [comment]
@mgfeller Lets add your profile to the meshkit and adapter-library PR template, so that you are not missed with any of the changes that come in. I think it was a mistake from my side that you weren't aware. We should also create a label, which says if the changes needs to be propagated right away to the components that uses meshkit/adapter-library.

**Comment by kumarabd** [comment]
Lets revert this change for now and work towards it? I apologise for this.

**Comment by mgfeller** [comment]
> Lets revert this change for now and work towards it? I apologise for this. It’s frustrating to me that any amount of your time isn’t optimally spent. Will make sure this doesn't happen in the future.

Ok, thanks @kumarabd !

**Pull request merged**
